#!/usr/bin/env python3
"""Search local ComfyUI official docs snapshot generated by sync_official_docs.py."""

from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Literal, Sequence


@dataclass
class ManifestRow:
    url: str
    local_path: str
    status: str
    sha256: str


@dataclass
class Match:
    score: int
    title: str
    url: str
    file_path: Path
    snippet: str


@dataclass(frozen=True)
class TaskPreset:
    path_prefixes: tuple[str, ...]
    description: str


EN_STOPWORDS = {
    "a",
    "an",
    "and",
    "are",
    "as",
    "at",
    "be",
    "by",
    "for",
    "from",
    "how",
    "in",
    "is",
    "it",
    "of",
    "on",
    "or",
    "that",
    "the",
    "this",
    "to",
    "was",
    "were",
    "what",
    "when",
    "where",
    "which",
    "with",
}

SHORT_TERM_ALLOWLIST = {
    "2d",
    "3d",
    "ai",
    "api",
    "db",
    "en",
    "gpu",
    "id",
    "ip",
    "llm",
    "md",
    "ui",
    "url",
    "ux",
    "v1",
    "v2",
    "v3",
    "zh",
}


TASK_PRESETS = {
    "workflow": TaskPreset(
        path_prefixes=(
            "tutorials/basic/",
            "tutorials/controlnet/",
            "tutorials/flux/",
            "tutorials/utility/",
            "tutorials/video/",
            "tutorials/3d/",
            "built-in-nodes/",
            "specs/",
            "development/core-concepts/",
            "interface/",
        ),
        description="Workflow design, built-in nodes, templates, and workflow JSON schema.",
    ),
    "node": TaskPreset(
        path_prefixes=(
            "built-in-nodes/",
            "tutorials/basic/",
            "tutorials/controlnet/",
            "tutorials/flux/",
            "tutorials/utility/",
            "tutorials/video/",
            "tutorials/3d/",
            "development/core-concepts/",
            "custom-nodes/",
        ),
        description="Official node lookup and node-level behavior.",
    ),
    "server": TaskPreset(
        path_prefixes=("development/comfyui-server/",),
        description="Self-hosted ComfyUI server routes, messages, and execution behavior.",
    ),
    "cloud": TaskPreset(
        path_prefixes=(
            "development/cloud/",
            "api-reference/cloud/",
            "cloud/",
            "account/",
        ),
        description="Comfy Cloud APIs, auth, jobs, files, workflows, and assets.",
    ),
    "custom-node": TaskPreset(
        path_prefixes=(
            "custom-nodes/",
            "manager/",
            "installation/install_custom_node.md",
            "troubleshooting/custom-node-issues.md",
            "registry/",
            "development/core-concepts/custom-nodes.md",
            "development/core-concepts/nodes.md",
            "development/core-concepts/properties.md",
        ),
        description="Custom node install, debugging, authoring, and migration guidance.",
    ),
    "registry": TaskPreset(
        path_prefixes=("registry/", "api-reference/registry/"),
        description="Registry publishing flow, node metadata, versions, and publisher APIs.",
    ),
    "install": TaskPreset(
        path_prefixes=("installation/", "manager/", "troubleshooting/", "support/"),
        description="Installation, updates, manager usage, and operational fixes.",
    ),
    "troubleshoot": TaskPreset(
        path_prefixes=("troubleshooting/", "installation/", "manager/", "support/"),
        description="Troubleshooting, break-fix, and recovery guidance.",
    ),
}


def load_manifest(manifest_path: Path) -> Dict[str, ManifestRow]:
    if not manifest_path.exists():
        raise FileNotFoundError(f"Manifest not found: {manifest_path}")
    lines = manifest_path.read_text(encoding="utf-8").splitlines()
    if not lines:
        return {}
    headers = lines[0].split("\t")
    col = {name: idx for idx, name in enumerate(headers)}
    required = {"url", "local_path", "status"}
    if not required.issubset(col):
        missing = ", ".join(sorted(required - set(col)))
        raise ValueError(f"Manifest missing required columns: {missing}")

    rows: Dict[str, ManifestRow] = {}
    for line in lines[1:]:
        parts = line.split("\t")
        if len(parts) < len(headers):
            parts += [""] * (len(headers) - len(parts))
        local_path = parts[col["local_path"]]
        rows[local_path] = ManifestRow(
            url=parts[col["url"]],
            local_path=local_path,
            status=parts[col["status"]],
            sha256=parts[col["sha256"]] if "sha256" in col else "",
        )
    return rows


def extract_title(text: str, fallback: str) -> str:
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return fallback


def build_query_terms(query: str) -> List[str]:
    raw = []
    for part in re.split(r"\s+", query.strip().lower()):
        term = re.sub(r"^\W+|\W+$", "", part)
        if term:
            raw.append(term)
    if not raw:
        return []

    filtered = [
        term
        for term in raw
        if term not in EN_STOPWORDS and (len(term) >= 3 or term in SHORT_TERM_ALLOWLIST)
    ]
    if not filtered:
        filtered = raw

    deduped: List[str] = []
    seen = set()
    for term in filtered:
        if term in seen:
            continue
        deduped.append(term)
        seen.add(term)
    return deduped


def is_snippet_noise_line(line: str) -> bool:
    stripped = line.strip().lower()
    return stripped in {
        "> ## documentation index",
        "> fetch the complete documentation index at: https://docs.comfy.org/llms.txt",
        "> use this file to discover all available pages before exploring further.",
    }


def make_snippet(lines: Sequence[str], match_index: int, radius: int) -> str:
    start = max(match_index - radius, 0)
    end = min(match_index + radius + 1, len(lines))
    chunk = [
        line.strip()
        for line in lines[start:end]
        if line.strip() and not is_snippet_noise_line(line)
    ]
    if not chunk:
        anchor = None
        for idx in range(start, len(lines)):
            if lines[idx].strip() and not is_snippet_noise_line(lines[idx]):
                anchor = idx
                break
        if anchor is not None:
            start2 = max(anchor - radius, 0)
            end2 = min(anchor + radius + 1, len(lines))
            chunk = [
                line.strip()
                for line in lines[start2:end2]
                if line.strip() and not is_snippet_noise_line(line)
            ]
    if not chunk:
        chunk = [line.strip() for line in lines[start:end] if line.strip()]
    return " | ".join(chunk)


def score_text(text: str, terms: Sequence[str]) -> tuple[int, int]:
    lower = text.lower()
    counts = [min(lower.count(term), 20) for term in terms]
    score = sum(counts)
    missing = len([count for count in counts if count == 0])
    return score, missing


def count_title_token_hits(title: str, terms: Sequence[str]) -> int:
    lower = title.lower()
    return sum(1 for term in terms if re.search(rf"\b{re.escape(term)}\b", lower))


def detect_doc_language(rel_path: str) -> Literal["en", "zh"]:
    first = rel_path.split("/", 1)[0].lower()
    if first.startswith("zh-cn"):
        return "zh"
    return "en"


def detect_doc_section(rel_path: str) -> str:
    return rel_path.split("/", 1)[0]


def matches_prefix_filter(rel_path: str, path_prefixes: Sequence[str]) -> bool:
    if not path_prefixes:
        return True
    lower_rel = rel_path.lower()
    for prefix in path_prefixes:
        normalized = prefix.strip().lower()
        if normalized and lower_rel.startswith(normalized):
            return True
    return False


def is_zhcn_alias_duplicate(
    rel_path: str,
    manifest_rows: Dict[str, ManifestRow],
    row: ManifestRow | None,
) -> bool:
    if row is None:
        return False
    lower_rel = rel_path.lower()
    if not lower_rel.startswith("zh-cn/"):
        return False
    base_rel = rel_path[6:]
    if not base_rel:
        return False
    base_row = manifest_rows.get(base_rel)
    if base_row is None:
        return False
    if row.status != "ok" or base_row.status != "ok":
        return False
    if not row.sha256 or not base_row.sha256:
        return False
    return row.sha256 == base_row.sha256


def search_snapshot(
    docs_dir: Path,
    manifest_rows: Dict[str, ManifestRow],
    query: str,
    top: int,
    context_lines: int,
    lang: Literal["all", "en", "zh"],
    section: str,
    path_prefixes: Sequence[str],
    dedupe_alias: bool,
) -> List[Match]:
    terms = build_query_terms(query)
    if not terms:
        return []

    results: List[Match] = []
    files = sorted(docs_dir.rglob("*.md"))
    section_filter = section.strip().lower()
    for file_path in files:
        rel = file_path.relative_to(docs_dir).as_posix()
        if not matches_prefix_filter(rel, path_prefixes):
            continue
        doc_section = detect_doc_section(rel).lower()
        if section_filter and doc_section != section_filter:
            continue
        doc_lang = detect_doc_language(rel)
        if lang != "all" and doc_lang != lang:
            continue

        manifest = manifest_rows.get(rel)
        if manifest is not None and manifest.status != "ok":
            continue
        if dedupe_alias and is_zhcn_alias_duplicate(rel, manifest_rows, manifest):
            continue

        try:
            text = file_path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        title_fallback = file_path.stem.replace("-", " ")
        title = extract_title(text, title_fallback)
        url = manifest.url if manifest is not None else f"https://docs.comfy.org/{rel[:-3]}"

        lower_text = text.lower()
        lower_title = title.lower()
        lower_url = url.lower()
        matched_terms = [term for term in terms if term in lower_text]
        matched_count = len(matched_terms)
        required_matches = max(1, (len(terms) + 1) // 2)
        if matched_count < required_matches:
            continue

        text_score, _ = score_text(text, terms)
        title_score = sum(1 for term in terms if term in lower_title)
        title_token_score = count_title_token_hits(title, terms)
        url_score = sum(1 for term in terms if term in lower_url)
        score = (
            text_score
            + (title_score * 26)
            + (title_token_score * 18)
            + (url_score * 15)
            + (matched_count * 12)
        )
        if matched_count == len(terms):
            score += 25
        if title_score == len(terms):
            score += 25

        lines = text.splitlines()
        lower_lines = [line.lower() for line in lines]
        best_idx = 0
        for idx, line in enumerate(lower_lines):
            if any(term in line for term in terms):
                best_idx = idx
                break
        snippet = make_snippet(lines, best_idx, context_lines)

        results.append(
            Match(
                score=score,
                title=title,
                url=url,
                file_path=file_path,
                snippet=snippet,
            )
        )

    results.sort(key=lambda item: (-item.score, item.title.lower(), str(item.file_path)))
    return results[:top]


def parse_args() -> argparse.Namespace:
    default_root = Path(__file__).resolve().parents[1] / "references"
    parser = argparse.ArgumentParser(description="Search local ComfyUI official docs snapshot.")
    parser.add_argument("query", help="Search query (plain keywords).")
    parser.add_argument(
        "--references-dir",
        default=str(default_root),
        help="References directory containing docs/ and docs-manifest.tsv.",
    )
    parser.add_argument("--top", type=int, default=10, help="Maximum results to return.")
    parser.add_argument(
        "--context-lines",
        type=int,
        default=1,
        help="How many surrounding lines to include around first match.",
    )
    parser.add_argument(
        "--lang",
        choices=["all", "en", "zh"],
        default="all",
        help="Language filter: all (default), en, or zh.",
    )
    parser.add_argument(
        "--section",
        default="",
        help="Top-level section filter (example: api-reference, tutorials, zh-CN).",
    )
    parser.add_argument(
        "--task",
        choices=sorted(TASK_PRESETS),
        default="",
        help=(
            "Task preset that narrows search to the most relevant doc families. "
            "Useful to keep server, cloud, registry, and workflow docs separate."
        ),
    )
    parser.set_defaults(dedupe_alias=True)
    parser.add_argument(
        "--no-dedupe-alias",
        action="store_false",
        dest="dedupe_alias",
        help="Do not suppress lowercase zh-cn alias pages that duplicate other paths.",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        dest="json_output",
        help="Output machine-readable JSON instead of plain text.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    references_dir = Path(args.references_dir).resolve()
    docs_dir = references_dir / "docs"
    manifest_path = references_dir / "docs-manifest.tsv"
    task = args.task.strip().lower()
    task_preset = TASK_PRESETS.get(task) if task else None

    if not docs_dir.exists():
        if args.json_output:
            payload = {
                "ok": False,
                "error": f"Docs snapshot not found at {docs_dir}.",
                "hint": "Run sync_official_docs.py first.",
            }
            print(json.dumps(payload, ensure_ascii=False, indent=2))
        else:
            print(
                f"Docs snapshot not found at {docs_dir}. Run sync_official_docs.py first.",
                file=sys.stderr,
            )
        return 2

    try:
        manifest_rows = load_manifest(manifest_path) if manifest_path.exists() else {}
        matches = search_snapshot(
            docs_dir=docs_dir,
            manifest_rows=manifest_rows,
            query=args.query,
            top=max(args.top, 1),
            context_lines=max(args.context_lines, 0),
            lang=args.lang,
            section=args.section,
            path_prefixes=task_preset.path_prefixes if task_preset is not None else (),
            dedupe_alias=bool(args.dedupe_alias),
        )
    except (FileNotFoundError, ValueError, OSError, UnicodeDecodeError) as exc:
        if args.json_output:
            payload = {
                "ok": False,
                "error": f"Invalid docs snapshot: {exc}",
                "hint": "Fix it with: python3 scripts/sync_official_docs.py --clean",
            }
            print(json.dumps(payload, ensure_ascii=False, indent=2))
        else:
            print(f"Invalid docs snapshot: {exc}", file=sys.stderr)
            print(
                "Fix it with: python3 scripts/sync_official_docs.py --clean",
                file=sys.stderr,
            )
        return 2

    if not matches:
        if args.json_output:
            payload = {
                "ok": True,
                "query": args.query,
                "language": args.lang,
                "section": args.section,
                "task": task,
                "results_count": 0,
                "results": [],
            }
            print(json.dumps(payload, ensure_ascii=False, indent=2))
        else:
            print("No matches found.")
        return 1

    if args.json_output:
        payload = {
            "ok": True,
            "query": args.query,
            "language": args.lang,
            "section": args.section,
            "task": task,
            "results_count": len(matches),
            "results": [
                {
                    "rank": idx,
                    "score": item.score,
                    "title": item.title,
                    "url": item.url,
                    "file": str(item.file_path),
                    "snippet": item.snippet,
                }
                for idx, item in enumerate(matches, start=1)
            ],
        }
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        return 0

    print(f'Query: "{args.query}"')
    print(f"Language: {args.lang}")
    if task_preset is not None:
        print(f"Task: {task} ({task_preset.description})")
    if args.section:
        print(f"Section: {args.section}")
    print(f"Results: {len(matches)}")
    print("")
    for idx, item in enumerate(matches, start=1):
        print(f"{idx}. [{item.score}] {item.title}")
        print(f"   URL: {item.url}")
        print(f"   File: {item.file_path}")
        if item.snippet:
            print(f"   Snippet: {item.snippet}")
        print("")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
